name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Railway
        uses: railwayapp/actions@v1
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
          project_id: 4f69a0a3-1d8b-4806-bca3-1d8eaf51e272
          environment: production